# Site settings
title: Jaclyn Pasquale
email: jaclynpasquale@gmail.com
description: # this means to ignore newlines until "baseurl:"
  The blog and portfolio of Jaclyn Pasquale. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://jaclynpasquale.github.io" # the base hostname & protocol for your site
twitter_username: deadleveldame
github_username:  JaclynPasquale

# Build settings
markdown: kramdown
